---
title: "BU_All_AlveolarDensity_Diagnosis_Interaction"
author: "Jake Kantrowitz"
date: "02/27/2017"
output: html_document
---

This analysis will focus on the fibroblastic foci score in IPF only

# Setup
```{r setup}
# set the repoDir to be the 'ipfcore' repo directory
repoDir <- "/protected/projects/pulmseq/Genentech_IPF_Analysis/ipfcore/"
# move to the repoDir so everything can be loaded and saved appropriately
setwd(repoDir)
source("analysis/BU_Analysis_Setup.r")

```

# Run the analysis
```{r analysis}
dds2 <- dds
dds2$lnBCell <- log(dds2$Bcell.CD79a.)
dds2$lnBCell <- dds2$lnBCell + -min(dds2$lnBCell)
#targetDds$lnFibFoc <- -log(targetDds$Fibroblastic.Foci)

# plot the variable(s) to use
plot(dds2$Bcell.CD79a. ~ dds2$TISSUE_DIAGNOSIS, col=c("grey90", "grey20"),
     cex.main=2, cex.lab=1.8, cex.axis=1.6,
     xlab="Diagnosis", ylab="B Cell CD79A",
     main="B Cell CD79A by Diagnosis")

plot(dds2$lnBCell ~ dds2$TISSUE_DIAGNOSIS, col=c("grey90", "grey20"),
     cex.main=2, cex.lab=1.8, cex.axis=1.6,
     xlab="Diagnosis", ylab="Log of B Cell CD79A",
     main="Log of B Cell CD79A by Diagnosis")

# setup the analysis options
#covariates <- c("NESTED_PATIENT", "TISSUE_DIAGNOSIS", "NESTED_PATIENT:TISSUE_DIAGNOSIS", "AlveolarSurfaceDensityperMicro.y")
#varOfInt <- "TISSUE_DIAGNOSIS:AlveolarSurfaceDensityperMicro.y"

#deseqAnalysis(targetDds, covariates = covariates, varOfInt = varOfInt,
#              fdr = 0.2, filename = "IPF_only_fibroblastic_foci",
#              genesets.save = T, enrichr.run = T, enrichr.fdr = 0.25)


m2 <- model.matrix(~TISSUE_DIAGNOSIS + TISSUE_DIAGNOSIS:NESTED_PATIENT + lnBCell, colData(dds2))
m2 <- m2[ ,-which(apply(unname(m2), 2, sum)==0)]

m3 <- model.matrix(~TISSUE_DIAGNOSIS + TISSUE_DIAGNOSIS:NESTED_PATIENT + lnBCell + TISSUE_DIAGNOSIS:lnBCell, colData(dds2))
m3 <- m3[ ,-which(apply(unname(m3), 2, sum)==0)]

varOfInt <- "ln.BCell.interaction"
dds4 <- DESeq(dds2, full=m3, reduced=m2, test="LRT")


temp <- deseqFinish(dds4, varOfInt = "TISSUE_DIAGNOSIS:lnBCell", fdr = 0.25, filename = "ln.BCell.interaction", genesets.save = T, enrichr.run = T, enrichr.fdr = 0.25)

```


